# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leWWeIypF2JoIZQ5XBv-SLP2hMUP1JMr
"""

!pip install ultralytics

from ultralytics import YOLO

# Load a model
model = YOLO("yolo11n-cls.yaml")  # load a pretrained model (recommended for training)

# Train the model
results = model.train(data="fashion-mnist", epochs=25, imgsz=28)

from ultralytics import YOLO
model=YOLO("yolov8n-cls.pt")
model=YOLO("/content/runs/classify/train2/weights/best.pt")

results=model.predict(source="/content/datasets/fashion-mnist/test/0/1060.png",save=True)

